= visoma-cli

A CLI utility for interacting with https://www.visoma.net/tickets[Visoma].

== Getting started

. Download and unpack the latest https://github.com/andreaslongo/visoma-cli/releases[binary release] for your platform:
** *Linux*: https://github.com/andreaslongo/visoma-cli/releases/latest/download/visoma-cli-x86_64-unknown-linux-musl.tar.gz[visoma-cli-x86_64-unknown-linux-musl.tar.gz]
** *Windows*: https://github.com/andreaslongo/visoma-cli/releases/latest/download/visoma-cli-x86_64-pc-windows-msvc.zip[visoma-cli-x86_64-pc-windows-msvc.zip]

. Open a terminal and run the program.

[,console]
----
$ ./visoma-cli --help      # Linux
$ .\visoma-cli.exe --help  # Windows
----

== Features

=== Creating new tickets

[,console]
----
Linux (Bash):
$ ./visoma-cli ticket new \
    --dry-run \
    --server visoma.example.com \
    --user visoma_user \
    --password 'visoma_password' \
    --title 'New Ticket' \
    --description 'A new ticket' \
    --customer-id 1 \
    --address-id 2

Windows (Powershell):
$ .\visoma-cli.exe ticket new `
    --dry-run `
    --server visoma.example.com `
    --user visoma_user `
    --password 'visoma_password' `
    --title 'New Ticket' `
    --description 'A new ticket' `
    --customer-id 1 `
    --address-id 2
----

NOTE: Use `--arranger-id <user id>` to assing the ticket to another (pool) user.

== Changelog

All notable changes will be documented here.

The format is based on https://keepachangelog.com/en/1.1.0/[Keep a Changelog],
and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

=== [0.2.2] - 2024-07-10

==== Changed

* Improve error messages.

=== [0.2.1] - 2024-07-02

==== Added

* More useful error messages.

=== [0.2.0] - 2024-07-01

==== Added

* Optional argument `--arranger-id` to the `ticket new` command for assigning the ticket to a user other than the creator of the ticket.

=== [0.1.0] - 2024-06-28

Initial release.

== Contributing

The best way to get started is to build and run a local dev container.

You can use https://podman.io[Podman] or any other OCI compliant container manager.
The dev container has all the required dependencies for working with the project.

[,console]
----
$ container/build.sh
$ container/run.sh
----

From inside the container, you can then run some workflows.

[,console]
----
$ cargo fmt && cargo clippy --all-targets  # run code formatter and linter
$ cargo test  # run tests
$ cargo doc   # build the docs
$ cargo run   # run the binary crate
----

=== Useful resources

* https://github.com/andreaslongo/learn-rust

== License

Copyright (C) 2024 Andreas Longo

GNU General Public License v3.0 or later
