name: "Release"

# Only run when a new tag is pushed
on:
  push:
    branches:
      - '!*'
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add x86_64-unknown-linux-musl
      - run: cargo build --release --target x86_64-unknown-linux-musl
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
      - run: tar -czvf template-rust-x86_64-unknown-linux-musl.tar.gz --directory target/x86_64-unknown-linux-musl/release template-rust
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-linux
          path: template-rust-x86_64-unknown-linux-musl.tar.gz

  build-windows:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add x86_64-pc-windows-msvc
      - run: cargo build --release --target x86_64-pc-windows-msvc
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
      - run: Compress-Archive -Path target/x86_64-pc-windows-msvc/release/template-rust.exe -Destination template-rust-x86_64-pc-windows-msvc.zip
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-windows
          path: template-rust-x86_64-pc-windows-msvc.zip

  release:
    needs: ["build-linux", "build-windows"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact-linux
      - uses: actions/download-artifact@v3
        with:
          name: artifact-windows
      - uses: softprops/action-gh-release@v1
        with:
          files: |
              template-rust-x86_64-unknown-linux-musl.tar.gz
              template-rust-x86_64-pc-windows-msvc.zip
